name: Matrix Build Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename binary
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/keylight target/release/keylight-linux
      - name: Rename binary
        if: matrix.os == 'macos-latest'
        run: mv target/release/keylight target/release/keylight-macos
      - name: Rename binary
        if: matrix.os == 'windows-latest'
        run: mv target/release/keylight.exe target/release/keylight.exe

      - name: Upload cli
        uses: actions/upload-artifact@v4
        with:
          name: keylightbuild-${{ matrix.os }}
          path: |
            target/release/keylight-linux
            target/release/keylight-macos
            target/release/keylight.exe
  
  # publish:
  #   name: Publish Release
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: keylightbuild-ubuntu-latest
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: keylightbuild-macos-latest
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: keylightbuild-windows-latest
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         files: |
  #           keylight.exe
  #           keylight-linux
  #           keylight-macos